export const data = [
  {
    id: 1,
    key: 'question_text',
    title: 'Question Text',
    editor: true,
  },
  {
    id: 2,
    key: 'question_image',
    title: 'Question Image',
    image: true,
  },
  {
    id: 3,
    key: 'answer_explanation',
    title: 'Answer Explanation',
    editor: true,
  },
  {
    id: 4,
    key: 'answer_explanation_image',
    title: 'Answer Explanation Image',
    image: true,
  },
  {
    id: 5,
    key: 'examName',
    title: 'Exam Name',
    type: 'text',
  },
  {
    id: 6,
    key: 'subject',
    title: 'Subject',
    type: 'text',
  },
  {
    id: 7,
    key: 'subcategory',
    title: 'Subcategory',
    type: 'text',
  },
  {
    id: 8,
    key: 'source',
    title: 'Source',
    type: 'url',
    link: true,
  },
  {
    id: 10,
    key: 'typeOfQuestion',
    title: 'Type of Question',
    dropdown: true,
    data: [
      { value: '', label: 'Select Type of Question' },
      { value: 'MCQ', label: 'MCQ' },
      { value: 'True/False', label: 'True/False' },
      { value: 'Fill in the blanks', label: 'Fill in the blanks' },
      { value: 'Match the following', label: 'Match the following' },
      { value: 'One word', label: 'One word' },
      { value: 'Assertion Reason', label: 'Assertion Reason' },
      { value: 'Others', label: 'Others' },
    ],
  },
  {
    id: 11,
    key: 'DifficultyLevel',
    title: 'Difficulty Level',
    dropdown: true,
    data: [
      { value: '', label: 'Select Difficulty Level' },
      { value: 'Easy', label: 'Easy' },
      { value: 'Medium', label: 'Medium' },
      { value: 'Hard', label: 'Hard' },
    ],
  },
  {
    id: 12,
    key: 'DiscriminatingFactor',
    title: 'Discriminating Factor',
    dropdown: true,
    data: [
      { value: '', label: 'Select Discriminating Factor' },
      { value: 'Easy', label: 'Easy' },
      { value: 'Medium', label: 'Medium' },
      { value: 'Hard', label: 'Hard' },
    ],
  },
];
